
name: Dockerized

on:
  push:
    branches:
      - master

jobs:
  dockerize:
    name: Dockerized
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Download
      #   run: |
      #     echo "Download model from google drive"
      #     chmod +x ./scripts/download-model.sh
      #     ./scripts/download-model.sh
      - name: Dockerized
        run: |
          echo 'Building docker image $IMAGE_REPOSITORY:$IMAGE_TAG'
          ls detection/vinai-phoBERT
          chmod +x ./scripts/dockerize.sh
          ./scripts/dockerize.sh $IMAGE_TAG $IMAGE_REPOSITORY
        env:
          IMAGE_TAG: m-${{ github.sha }}
          IMAGE_REPOSITORY: truongquangkhang/toxicity-detection