
name: Dockerized

on:
  push:
    branches:
      - master

jobs:
  dockerize:
    name: Dockerized
    runs-on: ubuntu-latest
    steps:
      - name: Download-Model
        run: |
          chmod +x ./scripts/download-model.sh
          ./scripts/download-model.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dockerized
        run: |
          echo 'Building docker image $IMAGE_REPOSITORY:$IMAGE_TAG'
          chmod +x ./scripts/dockerize.sh
          ./scripts/dockerize.sh $IMAGE_TAG $IMAGE_REPOSITORY
        env:
          IMAGE_TAG: m-${{ github.sha }}
          IMAGE_REPOSITORY: truongquangkhang/toxicity-detection